package org.apache.cxf.client;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * HelloService service = new HelloService();
 * HelloService portType = service.getHelloServicePort();
 * portType.sayHi(...);
 * </pre>
 * 
 * </p>
 * 
 */
@WebServiceClient(name = "HelloService", targetNamespace = "http://service.cxf.apache.org/", wsdlLocation = "http://localhost:8111/helloWorld?wsdl")
public class HelloService_Service extends Service
{

	public final static URL HELLOSERVICE_WSDL_LOCATION;
	private final static Logger logger = Logger
			.getLogger(org.apache.cxf.client.HelloService_Service.class
					.getName());

	static
	{
		URL url = null;
		try
		{
			URL baseUrl;
			baseUrl = org.apache.cxf.client.HelloService_Service.class
					.getResource(".");
			url = new URL(baseUrl,
					"http://localhost:8111/helloWorld?wsdl");
		} catch (MalformedURLException e)
		{
			logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8111/helloWorld?wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		HELLOSERVICE_WSDL_LOCATION = url;
	}

	public HelloService_Service(URL wsdlLocation, QName serviceName)
	{
		super(wsdlLocation, serviceName);
	}

	public HelloService_Service()
	{
		super(HELLOSERVICE_WSDL_LOCATION, new QName(
				"http://service.cxf.apache.org/",
				"HelloService"));
	}

	/**
	 * 
	 * @return returns HelloService
	 */
	@WebEndpoint(name = "HelloServicePort")
	public HelloService getHelloServicePort()
	{
		return super.getPort(new QName(
				"http://service.cxf.apache.org/",
				"HelloServicePort"), HelloService.class);
	}

}
