package org.apache.cxf.client;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;

import org.apache.cxf.bean.User;

/**
 * This class was generated by Apache CXF 3.1.0 2015-05-12T17:15:26.041+08:00
 * Generated source version: 3.1.0
 * 
 */
public final class HelloService_HelloServicePort_Client
{

	private static final QName SERVICE_NAME = new QName("http://service.cxf.apache.org/", "HelloService");

	private HelloService_HelloServicePort_Client()
	{
	}

	public static void main(String args[]) throws java.lang.Exception
	{
		URL wsdlURL = HelloService_Service.HELLOSERVICE_WSDL_LOCATION;
		if (args.length > 0 && args[0] != null && !"".equals(args[0]))
		{
			File wsdlFile = new File(args[0]);
			try
			{
				if (wsdlFile.exists())
				{
					wsdlURL = wsdlFile.toURI().toURL();
				} else
				{
					wsdlURL = new URL(args[0]);
				}
			} catch (MalformedURLException e)
			{
				e.printStackTrace();
			}
		}

		HelloService_Service ss = new HelloService_Service(wsdlURL, SERVICE_NAME);
		HelloService port = ss.getHelloServicePort();

		
		System.out.println("Invoking getListUser...");
		java.util.List<User> users = port.getListUser();
		System.out.println("size：" + users.size());
		System.out.println("getListUser.result=" + users);
		
		System.out.println("============================================================");
		System.out.println("Invoking getUser...");
		User _getUser_arg0 = users.get(0);
		java.lang.String _getUser__return = port.getUser(_getUser_arg0);
		System.out.println("getUser.result=" + _getUser__return);
		
		System.out.println("============================================================");
		System.out.println("Invoking sayHi...");
		java.lang.String _sayHi_arg0 = "123123123123";
		java.lang.String _sayHi__return = port.sayHi(_sayHi_arg0);
		System.out.println("sayHi.result=" + _sayHi__return);

		System.exit(0);
	}

}
